format_version: 10
pipelines:
  prometheus:
    group: defaultGroup
    display_order: -1
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/tool-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec:
                    arguments:
                      - i
                      - prometheus.dkdevops.online,
                      - -e
                      - ansible_user=ec2-user
                      - -e
                      - ansible_password=DevOps321
                      - prometheus.yml
                    command: ansible-playbook
                    run_if: passed
