format_version: 10
pipelines:
  tools-tf-apply:
    group: Tools
    display_order: -1
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/tool-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - APPLY:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            terraform:
              tasks:
                - exec:
                    arguments:
                      - init
                    command: terraform
                    run_if: passed
                - exec:
                    arguments:
                      - apply
                      - -auto-approve
                    command: terraform
                    run_if: passed
