format_version: 10
pipelines:
  vault:
    group: Tools
    display_order: -1
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/tool-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec:
                    arguments:
                      - -i
                      - vault-internal.dkdevops.online,
                      - -e
                      - ansible_user=ec2-user
                      - -e
                      - ansible_password=DevOps321
                      - tools.yml
                      - -e
                      - role_name=vault
                    command: ansible-playbook
                    run_if: passed
