- name: Set prompt
  ansible.builtin.shell: set-prompt vault

- name: get the Repo
  ansible.builtin.shell:
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

#- name: Add repository
#  ansible.builtin.yum_repository:
#    name: vault
#    description: vault repo
#    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Start vault
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: true
    daemon-reload: true