- name: Set prompt
  ansible.builtin.shell: set-prompt CI

- name: Create runner directory
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory

#- name: Download runner
#  ansible.builtin.unarchive:
#    src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
#    dest: /home/ec2-user/github-runner
#    remote_src: yes
#  become_user: ec2-user

- name: Download runner
  ansible.builtin.shell:
    curl -o /home/ec2-user/github-runner/actions-runner-linux-x64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz

#- name: Download runner
#  ansible.builtin.unarchive:
#    src: /opt/actions-runner-linux-x64-2.321.0.tar.gz
#    dest: /home/ec2-user/github-runner
#    owner: ec2-user
#    group: ec2-user

- name: Extract Runner
  ansible.builtin.shell:
    tar xzf /home/ec2-user/github-runner/actions-runner-linux-x64-2.321.0.tar.gz -C /home/ec2-user/github-runner

- name: Install dependencies
  ansible.builtin.shell:
    /home/ec2-user/github-runner/bin/installdependencies.sh

- name: Install Runner
  ansible.builtin.shell: ./config.sh --unattended --replace --url https://github.com/Devops-Stage-1 --token {{ secrets.GITHUB_RUNNER_TOKEN }}
  args:
    chdir: /home/ec2-user/github-runner

- name: Create the Runner
  ansible.builtin.shell:
    ./svc.sh install ; ./svc.sh start
  args:
    chdir: /home/ec2-user/github-runner

- name: Disable default NodeJS Version Module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS module for V20
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Download and unarchive sonarscanner
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
    dest: /opt
    remote_src: yes

- name: Install zip
  ansible.builtin.dnf:
    name: zip
    state: installed