- name: download and extract prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name: Copy config file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start the backend service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: true
    daemon-reload: true