- name: Set prompt
  ansible.builtin.shell: set-prompt artifactory

- name: Download and extract Jfrog
  ansible.builtin.unarchive:
    src: https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/7.98.9/jfrog-artifactory-oss-7.98.9-linux.tar.gz
    dest: /opt
    remote_src: yes

- name: copy repo template
  ansible.builtin.template:
    src: artifactory.service
    dest: /etc/systemd/system/artifactory.service

- name: start the service
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes
    daemon-reload: true