- name: Set prompt
  ansible.builtin.shell: set-prompt artifactory

- name: copy repo template
  ansible.builtin.template:
    src: jfrog.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpm.repo

- name: install artifactory
  ansible.builtin.dnf:
    name: jfrog-artifactory-oss
    state: installed
    disable_gpg_check: true

- name: start the service
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes
    daemon-reload: true


#    wget https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo -O jfrog-artifactory-rpms.repo;
#    sudo mv jfrog-artifactory-rpms.repo /etc/yum.repos.d/;
#    sudo yum update && sudo yum install jfrog-artifactory-oss